image:
  name: debian:10-slim

services:
  - docker:dind

stages:
  - test
  - build
  - testbuild
  - publish

.install: &install
  - 'apt-get update && apt-get install -qy python3-pytest python3-pytest-cov python3-pytest-mock python3-pip mypy codespell make flake8 shunit2 git'
  - 'apt-get install -qy black || true'
  - python3 -m pip install flit

before_script: *install

unittests-python3.7:
  image: debian:10-slim
  stage: test
  script:
    - make unit-tests

unittests-python3.6:
  image: ubuntu:18.04
  stage: test
  script:
    - make unit-tests

style:
  stage: test
  script:
    - make style

typecheck:
  stage: test
  script:
    - make typecheck

codespell:
  stage: test
  script:
    - make codespell

build:
  stage: build
  script:
    - git status
    - rm -rf dist/
    - flit --debug build
  artifacts:
    paths:
      - dist/

integration:
  stage: testbuild
  dependencies:
    - build
  script:
    - python3 -m pip install dist/*.whl
    - make integration-tests TMV=1
