image:
  name: debian:10-slim

services:
  - docker:dind


.tuxmake:
  except:
    - schedules

stages:
  - test
  - build
  - testbuild
  - publish

.install: &install
  - 'apt-get update && apt-get install -qy python3-pytest python3-pytest-cov python3-pytest-mock python3-pip mypy codespell make flake8 shunit2 git'
  - 'apt-get install -qy black || true'
  - python3 -m pip install flit

before_script: *install

.unit-tests:
  extends: .tuxmake
  stage: test
  script:
    - make unit-tests

unit-tests-python3.7:
  extends: .unit-tests
  image: debian:10-slim

unit-tests-python3.6:
  extends: .unit-tests
  image: ubuntu:18.04

unit-tests-python3.7-arm64:
  extends: .unit-tests
  tags:
    - arm64
  image: debian:10-slim

unit-tests-python3.6-arm64:
  extends: .unit-tests
  tags:
    - arm64
  image: ubuntu:18.04

style:
  extends: .tuxmake
  stage: test
  script:
    - make style

typecheck:
  extends: .tuxmake
  stage: test
  script:
    - make typecheck

codespell:
  extends: .tuxmake
  stage: test
  script:
    - make codespell

docker-build-tests:
  extends: .tuxmake
  stage: test
  script:
    - make docker-build-tests

build:
  extends: .tuxmake
  stage: build
  script:
    - git status
    - rm -rf dist/
    - flit --debug build
  artifacts:
    paths:
      - dist/

.integration:
  extends: .tuxmake
  stage: testbuild
  dependencies:
    - build
  script:
    - python3 -m pip install dist/*.whl
    - make integration-tests TMV=1

integration-python3.7:
  extends: .integration
  image: debian:10-slim

integration-python3.6:
  extends: .integration
  image: ubuntu:18.04

integration-python3.7-arm64:
  extends: .integration
  tags:
    - arm64
  image: debian:10-slim

integration-python3.6-arm64:
  extends: .integration
  tags:
    - arm64
  image: ubuntu:18.04

.docker:
  image: docker:19.03.11-dind
  services:
    - name: docker:19.03.11-dind
  only:
    - schedules
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add make python3
    - cd support/docker/
    - ./configure
    - 'docker login --username="${DOCKER_USERNAME}" --password-stdin < "${DOCKER_PASSWORD_FILE}"'

docker-images-amd64:
  stage: build
  extends: .docker
  variables:
    TAG: "-amd64"
  script:
    - make publish-${DOCKER_IMAGES}

docker-images-arm64:
  stage: build
  extends: .docker
  tags:
     - arm64-dind
  variables:
    TAG: "-arm64"
  script:
    - make publish-${DOCKER_IMAGES}

docker-images-multiarch:
  stage: publish
  extends: .docker
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    ARCH_TAGS: "-amd64 -arm64"
  script:
    - make publish-multiarch-${DOCKER_IMAGES}
